# Generated by Django 4.1.1 on 2022-10-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateField()),
                ('description', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
